# Settings that the LAMMPS build will import when this package library is used
# See the README file for more explanation

python_SYSINC = -I/usr/include/python2.7
python_SYSLIB = -lpython2.7 -lnsl -ldl -lpthread -lutil -lm -Xlinker -export-dynamic
python_SYSPATH = 
